//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPS.SIRCE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosTrabajoSIRCE
    {
        public CentrosTrabajoSIRCE()
        {
            this.EmpresaCentrosTrabajoSIRCE = new HashSet<EmpresaCentrosTrabajoSIRCE>();
            this.ListaCentrosTrabajo = new HashSet<ListaCentrosTrabajo>();
            this.Listas = new HashSet<Listas>();
            this.Trabajadores = new HashSet<Trabajadores>();
        }
    
        public int CentroTrabajoSIRCEID { get; set; }
        public int CentroTrabajoID { get; set; }
    
        public virtual ICollection<EmpresaCentrosTrabajoSIRCE> EmpresaCentrosTrabajoSIRCE { get; set; }
        public virtual ICollection<ListaCentrosTrabajo> ListaCentrosTrabajo { get; set; }
        public virtual ICollection<Listas> Listas { get; set; }
        public virtual ICollection<Trabajadores> Trabajadores { get; set; }
    }
}
