//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPS.SIRCE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constancias
    {
        public int ConstanciaID { get; set; }
        public int ListaCentroTrabajoID { get; set; }
        public int CursoID { get; set; }
        public int TrabajadorID { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual ListaCentrosTrabajo ListaCentrosTrabajo { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
