//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPS.SIRCE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsecutivosUR
    {
        public int ConsecutivoURID { get; set; }
        public int UnidadResponsableID { get; set; }
        public int ConsecutivoDC4 { get; set; }
    }
}
