//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPS.SIRCE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public Cursos()
        {
            this.Constancias = new HashSet<Constancias>();
        }
    
        public int CursoID { get; set; }
        public string Nombre { get; set; }
        public byte Duracion { get; set; }
        public int AreaTematicaID { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public byte TipoAgenteCapacitadorID { get; set; }
        public string RegistroAgenteExterno { get; set; }
        public byte ModalidadCapacitacionID { get; set; }
        public int ObjetivoCapacitacionID { get; set; }
        public int EmpresaSIRCEID { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual AreasTematicas AreasTematicas { get; set; }
        public virtual ICollection<Constancias> Constancias { get; set; }
        public virtual EmpresasSIRCE EmpresasSIRCE { get; set; }
        public virtual ObjetivosCapacitacion ObjetivosCapacitacion { get; set; }
    }
}
