//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPS.SIRCE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaCentrosTrabajoSIRCE
    {
        public int EmpresaCentroTrabajoSIRCEID { get; set; }
        public int CentroTrabajoSIRCEID { get; set; }
        public int EmpresaSIRCEID { get; set; }
    
        public virtual CentrosTrabajoSIRCE CentrosTrabajoSIRCE { get; set; }
        public virtual EmpresasSIRCE EmpresasSIRCE { get; set; }
    }
}
