//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPS.SIRCE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormaTrabajador
    {
        public int NormaTrabajadorID { get; set; }
        public int TrabajadorID { get; set; }
        public int NormaCompetenciaID { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual NormasCompetencia NormasCompetencia { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
